version: '3.4'

services: 
  redis:
    image: redis:latest

  testsamlidp_idp:
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:4000/metadata.xml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:4000/auth/saml
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
      SAML_ISSUER: http://localhost:4000/metadata.xml
      SAML_CALLBACK_URL: http://localhost:4000/auth/saml/callback
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8080:8080"
    - "8443:8443"
    volumes:
      - ./assets/users.php:/var/www/simplesamlphp/config/authsources.php
    
  dropbox-outgoing-spike-proxy:
    image: registry.gitlab.com/yesodot/rnd/terminal-rabaz/shared/spike-proxy-service
    environment: 
      PORT: 8000
      USE_REDIS: 'true'
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: ${SPIKE_CLIENT_ID}
      SPIKE_CLIENT_SECRET: ${SPIKE_CLIENT_SECRET}
      SPIKE_URL: ${SPIKE_URL}
      SPIKE_PUBLIC_KEY_FULL_PATH: ${SPIKE_PUBLIC_KEY_FULL_PATH}
      SPIKE_REDIS_KEY_PREFIX: ${SPIKE_REDIS_KEY_PREFIX}
      PROXY_SERVICES: '[{"route":"/kartoffel/*","pathRewrite":{"^/kartoffel":""},"target":"${KARTOFFEL_URL}","audience":"kartoffel"}]'
    ports: 
      - 8000:8000
    volumes:
      - ./certificate/publicKey.pem:/usr/src/app/certificate/publicKey.pem